repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest stable version
    hooks:
      - id: black
        args: ["--line-length=88"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest stable version
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Use the latest stable version
    hooks:
      - id: flake8
