merge_method: linear
slices:
  - sources:
      - model: NousResearch/Llama-2-7b-chat-hf
        layer_range: [0, 31]  # Adjusted to match the common layers
      - model: /home/ubuntu/profiler/Downloaded_checkpoint_pintxo
        layer_range: [0, 31]
parameters:
  weight: 0.5  # Merge with equal weight
dtype: float16
tokenizer_source: NousResearch/Llama-2-7b-chat-hf
